### ISSUE TITLE
TYPO3 10.4: Error when invalidating cache

### ISSUE THREAD

**Issue by felixbuenemann** [toumoro/tm_cloudfront#4]
I tried the extension on TYPO3 10.4.20 and if I hide an entry from the News extension I get the following error>\:

> TypoScriptFrontendController must be constructed with a valid SiteLanguage object or a resolved site in the current request as fallback. None given.

The error goes away, if I deactivate the tm_cloudfront extension.

Tested with extension v1.0.7.

**Comment by simouel** [comment]
Sorry sir, I didn't notice this issue.
It should be fixed in the current 1.10

I'll ajust my notification settings.
