### ISSUE TITLE
TYPO3 11 Compatibility

### ISSUE THREAD

**Issue by siwa-pparzer** [toumoro/tm_cloudfront#5]
Is a compatibility for TYPO3 11 LTS planned?

**Comment by simouel** [comment]
We will but we currently don't have any TYPO3 11 to play with.
You might try the new 1.10. I've changed the code to use the sitefinder.

**Comment by gaumondp** [comment]
@siwa-pparzer, we're running Master on quite a huge website (millions pageviews/day) so maybe you should consider this fixed.
